trigger:
  - dev

pool:
  vmImage: ubuntu-latest

variables:
  NODE_VERSION: '18.x'
  TARGET_DIR: '/var/www/anti-cor'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: Install Node.js

- script: |
    npm ci
    npm run build
  displayName: Build Vite React App

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'hostinger-vps'
    sourceFolder: 'dist'
    contents: '**'
    targetFolder: $(TARGET_DIR)
    cleanTargetFolder: true
  displayName: Deploy static files to VPS