import { ThemeType } from '../contexts/ThemeContext';

export const getThemeClasses = (theme: ThemeType) => {
  const themeMap = {
    blue: {
      // mapped to project brand colors (primary/secondary/dark/light/bg/text)
      badge: 'bg-primary/20 border-secondary/40 text-secondary',
      gradientText: 'from-primary via-secondary to-dark',
      accent: 'text-primary',
      buttonGradient: 'from-primary to-secondary',
      buttonHover: 'hover:from-dark hover:to-primary',
      shadow: 'shadow-primary/30',
      moduleCard: 'hover:border-secondary/50',
      moduleIcon: 'from-primary to-secondary',
      moduleTitle: 'group-hover:text-primary',
      featureIcon: 'bg-primary/20 border-secondary/30',
      featureIconColor: 'text-primary',
      benefitBg: 'from-bg to-light',
      benefitBorder: 'border-light',
      checkColor: 'text-primary',
      stepBorder: 'hover:border-primary',
      stepNumber: 'text-primary/20',
      stepIcon: 'from-primary to-secondary',
      stepConnector: 'from-primary to-secondary',
      audienceGradient: ['from-primary to-secondary', 'from-secondary to-dark', 'from-dark to-primary', 'from-light to-primary'],
      audienceBorder: 'hover:border-primary',
      audienceTitle: 'group-hover:text-primary',
      ctaBg: 'from-dark via-primary to-secondary',
      navLogo: 'from-primary to-secondary',
      navLogoText: 'from-light to-secondary',
      navHover: 'hover:text-primary',
      navButton: 'from-primary to-secondary hover:from-dark hover:to-primary hover:shadow-primary/30',
      navMobileButton: 'hover:border-primary hover:text-primary',
      navMobileButtonSolid: 'from-primary to-secondary hover:from-dark hover:to-primary',
      footerLogo: 'from-primary to-secondary',
      footerLogoText: 'from-light to-secondary',
      footerSocial: 'hover:bg-primary',
      footerLink: 'hover:text-primary',
    },
    green: {
      badge: 'bg-emerald-500/20 border-emerald-400/40 text-emerald-300',
      gradientText: 'from-emerald-400 via-green-400 to-teal-400',
      accent: 'text-emerald-400',
      buttonGradient: 'from-emerald-600 to-green-600',
      buttonHover: 'hover:from-emerald-700 hover:to-green-700',
      shadow: 'shadow-emerald-500/30',
      moduleCard: 'hover:border-emerald-400/50',
      moduleIcon: 'from-emerald-500 to-green-500',
      moduleTitle: 'group-hover:text-emerald-400',
      featureIcon: 'bg-emerald-500/20 border-emerald-400/30',
      featureIconColor: 'text-emerald-400',
      benefitBg: 'from-emerald-50 to-green-50',
      benefitBorder: 'border-emerald-200',
      checkColor: 'text-emerald-600',
      stepBorder: 'hover:border-emerald-500',
      stepNumber: 'text-emerald-500/20',
      stepIcon: 'from-emerald-500 to-green-500',
      stepConnector: 'from-emerald-500 to-green-500',
      audienceGradient: ['from-emerald-500 to-green-500', 'from-green-500 to-teal-500', 'from-emerald-600 to-green-600', 'from-teal-500 to-emerald-500'],
      audienceBorder: 'hover:border-emerald-500',
      audienceTitle: 'group-hover:text-emerald-600',
      ctaBg: 'from-slate-900 via-slate-800 to-emerald-900',
      navLogo: 'from-emerald-500 to-green-600',
      navLogoText: 'from-emerald-400 to-green-400',
      navHover: 'hover:text-emerald-400',
      navButton: 'from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 hover:shadow-emerald-500/30',
      navMobileButton: 'hover:border-emerald-500 hover:text-emerald-400',
      navMobileButtonSolid: 'from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700',
      footerLogo: 'from-emerald-500 to-green-600',
      footerLogoText: 'from-emerald-400 to-green-400',
      footerSocial: 'hover:bg-emerald-600',
      footerLink: 'hover:text-emerald-400',
    },
    red: {
      badge: 'bg-red-500/20 border-red-400/40 text-red-300',
      gradientText: 'from-red-400 via-rose-400 to-orange-400',
      accent: 'text-red-400',
      buttonGradient: 'from-red-600 to-rose-600',
      buttonHover: 'hover:from-red-700 hover:to-rose-700',
      shadow: 'shadow-red-500/30',
      moduleCard: 'hover:border-red-400/50',
      moduleIcon: 'from-red-500 to-rose-500',
      moduleTitle: 'group-hover:text-red-400',
      featureIcon: 'bg-red-500/20 border-red-400/30',
      featureIconColor: 'text-red-400',
      benefitBg: 'from-red-50 to-rose-50',
      benefitBorder: 'border-red-200',
      checkColor: 'text-red-600',
      stepBorder: 'hover:border-red-500',
      stepNumber: 'text-red-500/20',
      stepIcon: 'from-red-500 to-rose-500',
      stepConnector: 'from-red-500 to-rose-500',
      audienceGradient: ['from-red-500 to-rose-500', 'from-rose-500 to-pink-500', 'from-red-600 to-rose-600', 'from-orange-500 to-red-500'],
      audienceBorder: 'hover:border-red-500',
      audienceTitle: 'group-hover:text-red-600',
      ctaBg: 'from-slate-900 via-slate-800 to-red-900',
      navLogo: 'from-red-500 to-rose-600',
      navLogoText: 'from-red-400 to-rose-400',
      navHover: 'hover:text-red-400',
      navButton: 'from-red-600 to-rose-600 hover:from-red-700 hover:to-rose-700 hover:shadow-red-500/30',
      navMobileButton: 'hover:border-red-500 hover:text-red-400',
      navMobileButtonSolid: 'from-red-600 to-rose-600 hover:from-red-700 hover:to-rose-700',
      footerLogo: 'from-red-500 to-rose-600',
      footerLogoText: 'from-red-400 to-rose-400',
      footerSocial: 'hover:bg-red-600',
      footerLink: 'hover:text-red-400',
    },
    dark: {
      badge: 'bg-slate-600/20 border-slate-500/40 text-slate-300',
      gradientText: 'from-slate-300 via-slate-200 to-slate-100',
      accent: 'text-slate-300',
      buttonGradient: 'from-slate-700 to-slate-600',
      buttonHover: 'hover:from-slate-800 hover:to-slate-700',
      shadow: 'shadow-slate-500/30',
      moduleCard: 'hover:border-slate-500/50',
      moduleIcon: 'from-slate-600 to-slate-500',
      moduleTitle: 'group-hover:text-slate-300',
      featureIcon: 'bg-slate-600/20 border-slate-500/30',
      featureIconColor: 'text-slate-300',
      benefitBg: 'from-slate-100 to-slate-200',
      benefitBorder: 'border-slate-300',
      checkColor: 'text-slate-700',
      stepBorder: 'hover:border-slate-500',
      stepNumber: 'text-slate-500/20',
      stepIcon: 'from-slate-600 to-slate-500',
      stepConnector: 'from-slate-600 to-slate-500',
      audienceGradient: ['from-slate-600 to-slate-500', 'from-slate-500 to-slate-400', 'from-slate-700 to-slate-600', 'from-slate-500 to-slate-600'],
      audienceBorder: 'hover:border-slate-500',
      audienceTitle: 'group-hover:text-slate-700',
      ctaBg: 'from-slate-950 via-slate-900 to-slate-800',
      navLogo: 'from-slate-600 to-slate-500',
      navLogoText: 'from-slate-400 to-slate-300',
      navHover: 'hover:text-slate-300',
      navButton: 'from-slate-700 to-slate-600 hover:from-slate-800 hover:to-slate-700 hover:shadow-slate-500/30',
      navMobileButton: 'hover:border-slate-500 hover:text-slate-300',
      navMobileButtonSolid: 'from-slate-700 to-slate-600 hover:from-slate-800 hover:to-slate-700',
      footerLogo: 'from-slate-600 to-slate-500',
      footerLogoText: 'from-slate-400 to-slate-300',
      footerSocial: 'hover:bg-slate-600',
      footerLink: 'hover:text-slate-300',
    },
    light: {
      badge: 'bg-slate-200/50 border-slate-300/60 text-slate-700',
      gradientText: 'from-slate-700 via-slate-600 to-slate-500',
      accent: 'text-slate-700',
      buttonGradient: 'from-slate-200 to-slate-300',
      buttonHover: 'hover:from-slate-300 hover:to-slate-400',
      shadow: 'shadow-slate-500/20',
      moduleCard: 'hover:border-slate-400/50',
      moduleIcon: 'from-slate-300 to-slate-400',
      moduleTitle: 'group-hover:text-slate-700',
      featureIcon: 'bg-slate-200/50 border-slate-300/50',
      featureIconColor: 'text-slate-700',
      benefitBg: 'from-slate-50 to-slate-100',
      benefitBorder: 'border-slate-200',
      checkColor: 'text-slate-600',
      stepBorder: 'hover:border-slate-400',
      stepNumber: 'text-slate-300/50',
      stepIcon: 'from-slate-300 to-slate-400',
      stepConnector: 'from-slate-300 to-slate-400',
      audienceGradient: ['from-slate-300 to-slate-400', 'from-slate-400 to-slate-500', 'from-slate-200 to-slate-300', 'from-slate-400 to-slate-300'],
      audienceBorder: 'hover:border-slate-400',
      audienceTitle: 'group-hover:text-slate-700',
      ctaBg: 'from-slate-200 via-slate-100 to-slate-50',
      navLogo: 'from-slate-300 to-slate-400',
      navLogoText: 'from-slate-700 to-slate-600',
      navHover: 'hover:text-slate-700',
      navButton: 'from-slate-200 to-slate-300 hover:from-slate-300 hover:to-slate-400 hover:shadow-slate-500/20',
      navMobileButton: 'hover:border-slate-400 hover:text-slate-700',
      navMobileButtonSolid: 'from-slate-200 to-slate-300 hover:from-slate-300 hover:to-slate-400',
      footerLogo: 'from-slate-300 to-slate-400',
      footerLogoText: 'from-slate-700 to-slate-600',
      footerSocial: 'hover:bg-slate-300',
      footerLink: 'hover:text-slate-700',
    },
  };

  return themeMap[theme];
};
